### ISSUE TITLE
Rx Carve Out field on Plan Details tab - UNKNOWN VALUE

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#347]
Hello,

This was reported by multiple BEs.  We are having a notable issue with the generator as a result of the move of the enhancements to Production.

On the Plan Details tab, the Rx Carve Out field is defaulted to UNKNOWN VALUE.  And, on top of this - it is preventing this plan from being generated.  Please see screenshots, and note that this is a Showstopper error as plans cannot be generated until this is resolved.

Please fix ASAP.

![unknown-3](https://cloud.githubusercontent.com/assets/13453008/14145808/3b73d454-f663-11e5-8c5e-aed97f74c5b8.png)
![unknown-4](https://cloud.githubusercontent.com/assets/13453008/14145809/3c351e48-f663-11e5-8ef7-a7310e92292b.png)

**Comment by TimHeasley** [comment]
Will, we will look into the issue and work on a fix.

**Comment by TimHeasley** [comment]
Will, the issue has been fixed and is ready for testing in Production. The new attribute Carve Out needed to be added to Production attributes.  Thanks.

**Comment by willdwyer** [comment]
Thanks, Tim.  This will be left open until we can verify this defect is resolved.

**Comment by willdwyer** [comment]
Not fixed.  See screenshot.  When entering a value of No in Carve Out field in Plan Details tab, the screenshotted error occurs.  This is still in Showstopper status, 

![unknown-5](https://cloud.githubusercontent.com/assets/13453008/14155642/8f01e872-f690-11e5-989c-c2a7dac48d60.png)

**Comment by TimHeasley** [comment]
Will, the attribute configuration that was afffecting POS plans has been updated.  
Ready for retest.

**Comment by willdwyer** [comment]
This will remain open until all BEs can verify this is resolved.

**Comment by willdwyer** [comment]
This appears to be fixed.  This defect is now closed.
